name: dbt
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

env:
  DBT_PROFILES_DIR: .
  DBT_GOOGLE_PROJECT: case-study-361214
  DBT_GOOGLE_BIGQUERY_DATASET: dbt
  DBT_GOOGLE_BIGQUERY_KEYFILE: /Users/tobiaslofgren/Desktop/dbt/case-study-user-creds.json

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
      #- uses: mwhitaker/dbt-action@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      #- name: Authenticate using service account
      #  run: 'echo "$KEYFILE" > ./.gcloud/dbt-service-account.json'
      #  shell: bash
      #  env:
      #    KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}
      - name: Install dependencies
        run: |
          pip install dbt-bigquery==1.0.0
          dbt deps
      - run: dbt --version
      - run: dbt debug --config-dir
      - name: run dbt
        run: dbt run --profiles-dir .
        #env:
          DBT_GOOGLE_BIGQUERY_KEYFILE: ${{ secrets.DBT_GOOGLE_BIGQUERY_KEYFILE_PATH }}
      #- run: dbt run --profiles-dir DBT_PROFILES_DIR
      - run: dbt test