name: dbt
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT: case-study-361214
  DBT_GOOGLE_BIGQUERY_DATASET: dbt
  DBT_GOOGLE_BIGQUERY_KEYFILE: ${{ secrets.DBT_GOOGLE_BIGQUERY_KEYFILE }}

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: mwhitaker/dbt-action@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"    
      - run: dbt --version
      - run: 'echo "$KEYFILE" > ./.gcloud/dbt-service-account.json'
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}
      - run: dbt deps
      - run: dbt run
      - run: dbt test