name: dbt
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

env:
  DBT_PROFILES_DIR: .
  DBT_GOOGLE_PROJECT: case-study-361214
  DBT_GOOGLE_BIGQUERY_DATASET: dbt
  #DBT_GOOGLE_BIGQUERY_KEYFILE_PATH: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE_PATH}}
  DBT_GOOGLE_BIGQUERY_KEYFILE_CONTENT: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
      #- uses: mwhitaker/dbt-action@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - name: Authenticate using service account
        run: 'echo $DBT_GOOGLE_BIGQUERY_KEYFILE_CONTENT > tmp_key.json && DBT_GOOGLE_BIGQUERY_KEYFILE=tmp_key.json'
        shell: bash
      - name: Install dependencies
        run: |
          pip install dbt-bigquery==1.0.0
          dbt deps
      - run: dbt --version
      - run: dbt debug --config-dir
      - run: env
      - name: run dbt
        run: dbt run --profiles-dir .
      #- run: dbt run --profiles-dir DBT_PROFILES_DIR
      - run: dbt test